// Generated by scripts/export-moment-art.cjs
export const MOMENT_ART_SOURCES = {
  creation: require('../assets/moment-placeholders/creation.svg'),
  fall: require('../assets/moment-placeholders/fall.svg'),
  flood: require('../assets/moment-placeholders/flood.svg'),
  stars: require('../assets/moment-placeholders/stars.svg'),
  joseph: require('../assets/moment-placeholders/joseph.svg'),
  book: require('../assets/moment-placeholders/book.svg'),
} as const;
