import { buttonStyles } from "@/lib/buttonStyles";
import { useReducedMotion } from "@/lib/useReducedMotion";
import { useEffect, useState } from "react";
import { Modal, Pressable, ScrollView, View } from "react-native";
import { Text, TextInput } from "@/components/CloserText";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useColors } from "@/state/theme";
export function ProfileVerse() {
  const reduced = useReducedMotion();
  const colors = useColors(), [saved,setSaved] = useState({text:"",reference:""}), [draft,setDraft] = useState(saved), [open,setOpen] = useState(false), [error,setError] = useState("");
  useEffect(()=>{ void AsyncStorage.getItem("closer.profile-verse.v1").then(v=>{if(v)setSaved(JSON.parse(v));}).catch(()=>{}); },[]);
  return <><Pressable accessibilityRole="button" onPress={()=>{setDraft(saved);setOpen(true);}} style={{marginHorizontal:20,marginBottom:28,padding:20,gap:8,borderRadius:18,backgroundColor:colors.surface}}><Text style={{fontSize:13,color:colors.inkMuted}}>Your verse</Text><Text style={{fontSize:17,lineHeight:25,color:colors.ink}}>{saved.text || "Pick a verse that feels like yours."}</Text>{!!saved.reference && <Text style={{color:colors.inkMuted,fontSize:14}}>{saved.reference}</Text>}</Pressable><Modal visible={open} presentationStyle="pageSheet" animationType={reduced ? "fade" : "slide"} onRequestClose={()=>setOpen(false)}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,gap:20}} style={{backgroundColor:colors.bg}}><Pressable accessibilityRole="button" onPress={()=>setOpen(false)} style={{alignSelf:"flex-end",minHeight:44,justifyContent:"center"}}><Text style={[{ color:colors.ink }, buttonStyles.compactLabel]}>Cancel</Text></Pressable><Text style={{fontSize:28,fontWeight:"700",color:colors.ink}}>Your verse</Text>{(["text","reference"] as const).map(key=><TextInput key={key} accessibilityLabel={key==="text"?"Verse text":"Bible reference"} placeholder={key==="text"?"Words you want to keep close":"e.g. Psalm 23:1"} placeholderTextColor={colors.inkMuted} multiline={key==="text"} maxLength={key==="text"?600:80} value={draft[key]} onChangeText={value=>setDraft(d=>({...d,[key]:value}))} style={{minHeight:key==="text"?140:54,padding:16,borderRadius:16,color:colors.ink,backgroundColor:colors.surface,fontSize:17}}/>)}{!!error&&<Text style={{color:colors.ink}}>{error}</Text>}<Pressable accessibilityRole="button" disabled={!draft.text.trim()||!draft.reference.trim()} onPress={async()=>{try{await AsyncStorage.setItem("closer.profile-verse.v1",JSON.stringify(draft));setSaved(draft);setOpen(false);}catch{setError("Couldn’t save. Please try again.");}}} style={{padding:18,borderRadius:28,backgroundColor:colors.ink,alignItems:"center",opacity:draft.text.trim()&&draft.reference.trim()?1:.4}}><Text style={[{ color:colors.bg }, buttonStyles.label]}>Save verse</Text></Pressable></ScrollView></Modal></>;
}
