import { uiText } from '@/lib/typography';
import { contentLayout } from '@/lib/contentStyles';
import { ProfileActivitySheet } from "./ProfileActivitySheet";
import { useRef, useState } from 'react';
import { Modal, Pressable, ScrollView, View, useWindowDimensions } from "react-native";
import { Text } from "@/components/CloserText";
import { Image, type ImageSource } from 'expo-image';
import { useRouter } from 'expo-router';
import Animated, { FadeInDown } from 'react-native-reanimated';
import Svg, { Path, Rect } from 'react-native-svg';
import { useResolvedScheme } from '@/state/theme';
import { useProgress } from '@/state/progress';
import { useAnnotations } from '@/state/annotations';
import { useBibleMomentCollection } from '@/state/bibleMoments';
import { useAchievements } from '@/lib/useAchievements';
import { buildCurrentWeek } from '@/lib/rhythm';
import { useReducedMotion } from '@/lib/useReducedMotion';
import { BIBLE_MOMENTS } from '@/constants/bibleMoments';
import { StreakFireAnimation } from './StreakFireAnimation';
import { EnamelAchievement } from './EnamelAchievement';
import { ReaderMomentArt } from './ReaderMomentArt';
import { ReaderMomentCardBox } from './ReaderMomentCardBox';
import { ReaderMaterialGradient } from './ReaderMaterialGradient';
import { ReaderSheet } from './ReaderSheet';
import { SheetHeading } from './SheetHeading';
import { SFSymbol } from './Symbol';
import * as haptics from '@/lib/haptics';

export const PROFILE_PALETTE = {
  light:{bg:'#FAF2E5',ink:'#35291F',muted:'#897766',surface:'#FFFBF4',line:'#DAC9B54A',green:'#2A8050'},
  dark:{bg:'#211D19',ink:'#FFF4E5',muted:'#BAA58F',surface:'#302920',line:'#BAA58F22',green:'#8BD5A2'},
};
/** The approved profile study, backed by the same stores as the reader and achievement shelf. */
export function ProfileJourney({name,joined,avatar,onAvatar,onSettings}:{name:string;joined:string|null;avatar?:ImageSource;onAvatar:()=>void;onSettings:()=>void}) {
  const router=useRouter(),dark=useResolvedScheme()==='dark',p=PROFILE_PALETTE[dark?'dark':'light'],reduced=useReducedMotion();
  const {fontScale,width}=useWindowDimensions(), {streak,engagedDates}=useProgress(),{counts}=useAnnotations(),{ids,hydrated}=useBibleMomentCollection(),{achievements}=useAchievements();
  const [pressedTile,setPressedTile]=useState<number|null>(null);
  const [activity,setActivity]=useState(false);
  const [collection,setCollection]=useState(false),[nextOpen,setNextOpen]=useState(false);
  const source=useRef<View>(null),week=buildCurrentWeek(engagedDates);
  const earned=achievements.filter(a=>a.value>=a.target).length;
  // Longest streak determines earned badges; current streak determines the next day's progress.
  const next=achievements.find(a=>a.category==='Streaks'&&a.value<a.target);
  const progress=next?Math.min(streak.current/next.target,1):1;
  const remaining=next?Math.max(0,next.target-streak.current):0;
  const arrival=(index:number)=>reduced?undefined:FadeInDown.delay(index*55).duration(500).springify().damping(22).stiffness(190);
  const go=(route:'/achievements'|'/highlights'|'/notes'|'/(tabs)/community'|'/rhythm')=>{haptics.soft();router.push(route);};
  const border={borderWidth:1,borderColor:p.line};
  const tileColors=dark?['#3C3049','#343D2C','#4A3B24','#293F39']:['#E8DEF1','#E5E9D6','#F2DFB5','#DFEBE7'];
  const tileInk=dark?['#ECDDFA','#E2EBD2','#F5DFB6','#D1E9DF']:['#49365C','#374B33','#695124','#315B51'];
  const tiles=[{title:'Achievements',detail:`${earned} keepsakes earned`,action:()=>go('/achievements')},{title:'Bible Moments',detail:hydrated?`${ids.length} discoveries`:'Loading your collection…',action:()=>{haptics.soft();setCollection(true);}},{title:'Highlights',detail:`${counts.highlights} verses to return to`,action:()=>go('/highlights')},{title:'My reflections',detail:`${counts.notes} notes along the way`,action:()=>go('/notes')}];
  return <View style={{paddingHorizontal:contentLayout.gutter,paddingTop:12}}>
    <View style={{flexDirection:width<440||fontScale>1.1?'column':'row',alignItems:width<440||fontScale>1.1?'flex-start':'center',justifyContent:'space-between',gap:12,marginBottom:24}}><Text accessibilityRole="header" style={{...uiText.screenTitle,color:p.ink,flexShrink:1}}>Your journey</Text><View style={{flexDirection:'row',gap:4}}><Pressable accessibilityRole="button" accessibilityLabel="Activity" onPress={()=>setActivity(true)} style={{width:44,height:44,borderRadius:22,backgroundColor:p.surface,alignItems:'center',justifyContent:'center'}}><SFSymbol name="bell" size={21} color={p.ink}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Settings" onPress={onSettings} style={{width:44,height:44,borderRadius:22,backgroundColor:p.surface,alignItems:'center',justifyContent:'center'}}><SFSymbol name="gearshape" size={21} color={p.ink}/></Pressable></View></View>
    <Animated.View entering={arrival(1)} style={{flexDirection:'row',alignItems:'center',gap:16,marginBottom:24}}><Pressable accessibilityRole="button" accessibilityLabel="Change profile avatar" onPress={onAvatar} style={{padding:4,borderRadius:34,backgroundColor:p.surface,...border}}>{avatar?<Image source={avatar} contentFit="cover" style={{width:58,height:58,borderRadius:29}}/>:<View style={{width:58,height:58,borderRadius:29,backgroundColor:'#E7CFAF',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:24,color:'#35291F',fontWeight:'600'}}>{name.charAt(0).toUpperCase()}</Text></View>}</Pressable><View style={{flex:1,gap:6}}><Text style={{...uiText.sectionTitle,color:p.ink}}>{name}</Text><Text style={{...uiText.supporting,color:p.muted}}>{joined?.replace('Joined ','Walking with God since ')??'A little space for your journey.'}</Text></View></Animated.View>
    <Animated.View entering={arrival(2)}><Pressable accessibilityRole="button" accessibilityLabel={`${streak.current} day streak. View your reading history`} onPress={()=>go('/rhythm')} style={{padding:18,borderRadius:23,backgroundColor:p.surface,...border,marginBottom:14}}><View style={{flexDirection:'row',gap:7,alignItems:'center'}}><View style={{width:50,marginLeft:-5}}><StreakFireAnimation size={66}/></View><View style={{flex:1,gap:5}}><Text style={{...uiText.sectionTitle,color:p.ink}}>{streak.current?`${streak.current} ${streak.current===1?'day':'days'}, showing up.`:'A little light starts here.'}</Text><Text style={{...uiText.supporting,color:p.muted}}>A little time with God. Every day.</Text></View></View><View style={{flexDirection:'row',justifyContent:'space-between',marginTop:17}}>{week.cells.map(cell=><View key={cell.dateISO} accessible accessibilityLabel={`${cell.dateISO}${cell.isToday?', today':''}, ${cell.state==='engaged'?'completed':'not completed'}`} style={{alignItems:'center',gap:7}}><Text style={{fontSize:13,lineHeight:18,color:p.muted}}>{new Date(cell.dateISO+'T12:00:00').toLocaleDateString(undefined,{weekday:'narrow'})}</Text><View style={{width:28,height:28,borderRadius:14,backgroundColor:cell.state==='engaged'?(dark?'#3B5140':'#DCEBDC'):p.line,alignItems:'center',justifyContent:'center',borderWidth:cell.isToday?1:0,borderColor:'#9FB29B'}}>{cell.state==='engaged'?<SFSymbol name="checkmark" size={12} color={p.green}/>:<Text style={{fontSize:12,color:p.muted}}>·</Text>}</View></View>)}</View></Pressable></Animated.View>
    <Animated.View entering={arrival(3)}><Pressable accessibilityRole="button" accessibilityLabel={next?`${next.title}. ${remaining} more ${remaining===1?'day':'days'} to earn it`:'View your achievements'} onPress={()=>next?setNextOpen(true):go('/achievements')} style={{borderRadius:23,overflow:'hidden',...border}}><ReaderMaterialGradient colors={dark?['#493721',p.surface]:['#F2E3C9',p.surface]} style={{width:'100%'}}><View style={{padding:15,flexDirection:'row',alignItems:'center',gap:8}}><EnamelAchievement size={94} achievementId={next?.id??'streak-100'}/><View style={{flex:1,gap:7}}><Text style={{fontSize:13,lineHeight:18,letterSpacing:1,fontWeight:'600',color:p.muted}}>YOUR {next?'NEXT KEEPSAKE':'KEEPSAKES'}</Text><Text style={{fontSize:18,fontWeight:'700',letterSpacing:-.4,color:p.ink}}>{next?.id==='streak-7'?'Seven faithful days':next?.title??'Look how far you’ve come'}</Text><Text style={{...uiText.supporting,color:p.muted}}>{next?`${remaining} more ${remaining===1?'day':'days'} to make it yours.`:'Little reminders of your journey.'}</Text><View accessibilityRole="progressbar" accessibilityValue={{min:0,max:next?.target??1,now:next?Math.min(streak.current,next.target):1}} style={{height:4,borderRadius:2,backgroundColor:p.line,overflow:'hidden',marginTop:5}}><View style={{width:`${progress*100}%`,height:4,backgroundColor:'#B98642'}}/></View></View><SFSymbol name="chevron.right" size={12} color={p.muted}/></View></ReaderMaterialGradient></Pressable></Animated.View>
    <View style={{marginTop:24,marginBottom:12,gap:4}}><Text accessibilityRole="header" style={{...uiText.sectionTitle,color:p.ink}}>Things you’ve kept</Text><Text style={{...uiText.supporting,color:p.muted}}>A little collection of you</Text></View>
    <View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>{tiles.map((tile,i)=><Animated.View key={tile.title} entering={arrival(4+i)} style={{width:fontScale>1.2||width<360?'100%':(width-contentLayout.gutter*2-12)/2}}><Pressable accessibilityRole="button" onPress={tile.action} onPressIn={()=>setPressedTile(i)} onPressOut={()=>setPressedTile(null)} style={{minHeight:159,borderRadius:21,backgroundColor:tileColors[i],padding:14,...border,opacity:pressedTile===i?.82:1,transform:[{scale:pressedTile===i?.98:1}]}}><View ref={i===1?source:undefined} collapsable={false} pointerEvents="none" style={{height:88,alignItems:'flex-end',justifyContent:'center'}}>{i===0?<EnamelAchievement size={102} achievementId="letters-1"/>:i===1?<View style={{width:112,height:88}}><View style={{position:'absolute',right:47,top:2,width:57,height:78,borderRadius:9,borderWidth:2,borderColor:'#D4AE78',backgroundColor:'#B75B3B',transform:[{rotate:'-12deg'}]}}/><View style={{position:'absolute',right:13,top:5,width:57,height:78,borderRadius:9,borderWidth:2,borderColor:'#D4AE78',overflow:'hidden',transform:[{rotate:'10deg'}]}}><ReaderMomentArt moment={BIBLE_MOMENTS[0]}/></View></View>:i===2?<View style={{width:95,height:80}}><View style={{position:'absolute',width:82,height:45,right:0,top:20,backgroundColor:'#E9AE3F70',borderRadius:10,transform:[{rotate:'-8deg'}]}}/><Text style={{fontFamily:'Georgia',fontSize:70,color:dark?'#F5DFB6':'#937329',position:'absolute',right:18,top:-5}}>“</Text></View>:<Svg width={80} height={80} viewBox="0 0 80 80"><Rect x={20} y={12} width={39} height={58} fill="#ffffff33" stroke={tileInk[i]}/><Path d="M28 26h21M28 35h21M28 44h15M49 57 65 24l6 3-16 33-8 5Z" stroke={tileInk[i]} fill="none"/></Svg>}</View><Text style={{...uiText.body,fontWeight:'800',color:tileInk[i],marginTop:7}}>{tile.title}</Text><Text style={{...uiText.supporting,color:tileInk[i],opacity:.8,marginTop:4}}>{tile.detail}</Text></Pressable></Animated.View>)}</View>
    <Pressable accessibilityRole="button" onPress={()=>go('/(tabs)/community')} style={{marginTop:20,padding:16,borderRadius:19,backgroundColor:p.surface,...border,flexDirection:'row',alignItems:'center',gap:12}}><View style={{width:35,height:35,borderRadius:18,backgroundColor:'#426B53',alignItems:'center',justifyContent:'center'}}><SFSymbol name="person.2" size={19} color="#EFF7E9"/></View><View style={{flex:1,gap:5}}><Text style={{...uiText.body,fontWeight:'800',color:p.ink}}>You don’t have to walk alone</Text><Text style={{...uiText.supporting,color:p.muted}}>Your community & study groups</Text></View><SFSymbol name="chevron.right" size={12} color={p.muted}/></Pressable>
    <ProfileActivitySheet visible={activity} onClose={()=>setActivity(false)}/>
    <Modal visible={collection} transparent animationType="none" onRequestClose={()=>setCollection(false)}>{collection&&<ReaderMomentCardBox bookId="genesis" pocketRef={source} onClose={()=>setCollection(false)}/>}</Modal>
    <ReaderSheet visible={nextOpen} onClose={()=>setNextOpen(false)} detents={[.65,1]} backgroundColor={p.bg}><ScrollView contentContainerStyle={{paddingHorizontal:24,paddingTop:32,paddingBottom:36,gap:22}}><SheetHeading title="Your next keepsake" onDone={()=>setNextOpen(false)}/><View style={{alignItems:'center'}}><EnamelAchievement size={195} achievementId={next?.id}/></View><Text style={{...uiText.sectionTitle,textAlign:'center',color:p.ink}}>{next?.title}</Text><Text style={{...uiText.body,color:p.muted,textAlign:'center'}}>You’re making room for something meaningful.{ '\n'}{remaining} more {remaining===1?'day':'days'} of showing up, and this keepsake is yours.</Text><View style={{height:4,borderRadius:2,backgroundColor:p.line,overflow:'hidden'}}><View style={{width:`${progress*100}%`,height:4,backgroundColor:'#B98642'}}/></View><Text style={{...uiText.supporting,textAlign:'center',color:p.muted}}>{streak.current} of {next?.target} days</Text></ScrollView></ReaderSheet>
  </View>;
}
