// Generated by scripts/export-achievement-art.cjs from the approved illustrated-v5 collection.
export const achievementArtwork = {
  "letters-1": { source: require('../assets/achievements/native/letters-1.png'), light: "#f4c9ab", dark: "#683444", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "letters-7": { source: require('../assets/achievements/native/letters-7.png'), light: "#b9edf1", dark: "#443071", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "letters-30": { source: require('../assets/achievements/native/letters-30.png'), light: "#ffd3fa", dark: "#40204e", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "letters-100": { source: require('../assets/achievements/native/letters-100.png'), light: "#ffe4aa", dark: "#442334", outline: "M150 24A126 126 0 1 1 149.9 24Z" },
  "streak-1": { source: require('../assets/achievements/native/streak-1.png'), light: "#ffe1a4", dark: "#452039", outline: "M150 22L252 60Q265 66 260 86L250 183Q247 232 150 280Q53 232 50 183L40 86Q35 66 48 60Z" },
  "streak-7": { source: require('../assets/achievements/native/streak-7.png'), light: "#f4d899", dark: "#614127", outline: "M150 22L252 60Q265 66 260 86L250 183Q247 232 150 280Q53 232 50 183L40 86Q35 66 48 60Z" },
  "streak-30": { source: require('../assets/achievements/native/streak-30.png'), light: "#d7c9f2", dark: "#373465", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "streak-100": { source: require('../assets/achievements/native/streak-100.png'), light: "#f5d492", dark: "#315d42", outline: "M150 22L252 60Q265 66 260 86L250 183Q247 232 150 280Q53 232 50 183L40 86Q35 66 48 60Z" },
  "chapter": { source: require('../assets/achievements/native/chapter.png'), light: "#f6e6ff", dark: "#302363", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "highlight": { source: require('../assets/achievements/native/highlight.png'), light: "#fff8b4", dark: "#383725", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "note": { source: require('../assets/achievements/native/note.png'), light: "#c4fff0", dark: "#073f47", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "listener": { source: require('../assets/achievements/native/listener.png'), light: "#e5c6ff", dark: "#302061", outline: "M150 24A126 126 0 1 1 149.9 24Z" },
  "genesis": { source: require('../assets/achievements/native/genesis.png'), light: "#bfdfe0", dark: "#1b4050", outline: "M150 24A126 126 0 1 1 149.9 24Z" },
  "express": { source: require('../assets/achievements/native/express.png'), light: "#fff0b4", dark: "#4e2427", outline: "M150 22L252 60Q265 66 260 86L250 183Q247 232 150 280Q53 232 50 183L40 86Q35 66 48 60Z" },
  "law": { source: require('../assets/achievements/native/law.png'), light: "#e2f7ff", dark: "#183c5b", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "bible": { source: require('../assets/achievements/native/bible.png'), light: "#d9ffdd", dark: "#103d39", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "moment": { source: require('../assets/achievements/native/moment.png'), light: "#d4bdf8", dark: "#354177", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "garden": { source: require('../assets/achievements/native/garden.png'), light: "#c9dfc9", dark: "#254b43", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "ten": { source: require('../assets/achievements/native/ten.png'), light: "#fff5b4", dark: "#4b2a31", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "all": { source: require('../assets/achievements/native/all.png'), light: "#f7e0ff", dark: "#302449", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
  "amen": { source: require('../assets/achievements/native/amen.png'), light: "#d1ddf3", dark: "#293e62", outline: "M150 24A126 126 0 1 1 149.9 24Z" },
  "honest": { source: require('../assets/achievements/native/honest.png'), light: "#ffe1f2", dark: "#4f1e41", outline: "M150 24A126 126 0 1 1 149.9 24Z" },
  "quiz": { source: require('../assets/achievements/native/quiz.png'), light: "#e4f7ff", dark: "#183856", outline: "M150 24A126 126 0 1 1 149.9 24Z" },
  "verse": { source: require('../assets/achievements/native/verse.png'), light: "#efffc7", dark: "#203e32", outline: "M150 22Q157 22 164 27L251 78Q261 83 261 95V205Q261 217 251 223L162 275Q150 282 139 275L49 223Q39 217 39 205V95Q39 83 49 78L137 27Q144 22 150 22Z" },
} as const;
export type AchievementArtId = keyof typeof achievementArtwork;

/** Legacy daily checkpoints share the corresponding earned streak tier. */
export function milestoneArtworkId(day: number): AchievementArtId {
  return day === 1 ? 'letters-1' : day < 7 ? 'streak-1' : day < 30 ? 'streak-7' : day < 100 ? 'streak-30' : 'streak-100';
}
